[package]
authors = ["Mathis Møller"]
description = "Common code for jotai SWC plugins"
license = "MIT"
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.198"
serde_json = "1.0.116"
swc_core = { version = "0.91.0", features = ["common", "ecma_ast"] }
